// AUTO-GENERATED by scripts/prepare-client-logos.mjs. Do not edit by hand.
//
// The intrinsic size of each normalised client logo. See that script for why
// these are generated rather than written down, and ClientsSection.css for
// what consumes them.

import develor from '@/assets/images/clients/develor.png';
import karras from '@/assets/images/clients/karras.png';
import starboard from '@/assets/images/clients/starboard.png';
import evivios from '@/assets/images/clients/evivios.png';
import goat from '@/assets/images/clients/goat.png';
import cityskal from '@/assets/images/clients/cityskal.png';
import psi from '@/assets/images/clients/psi.png';
import padel from '@/assets/images/clients/padel.png';

export interface ClientLogo {
  id: string;
  src: string;
  width: number;
  height: number;
}

export const CLIENT_LOGOS: Record<string, ClientLogo> = {
  develor: { id: 'develor', src: develor, width: 697, height: 88 },
  karras: { id: 'karras', src: karras, width: 217, height: 88 },
  starboard: { id: 'starboard', src: starboard, width: 303, height: 88 },
  evivios: { id: 'evivios', src: evivios, width: 413, height: 88 },
  goat: { id: 'goat', src: goat, width: 77, height: 88 },
  cityskal: { id: 'cityskal', src: cityskal, width: 133, height: 88 },
  psi: { id: 'psi', src: psi, width: 165, height: 88 },
  padel: { id: 'padel', src: padel, width: 219, height: 88 },
};
